version: '3.8'

services:
   php-httpd:
      container_name: php
      build:
         context: ./DocumentRoot/app
         dockerfile: Dockerfilephp
      image: php:8.1-apache
      ports:
         - 88:80
      volumes:
         - "./DocumentRoot/app/:/var/www/html"
         
   mariadb:
      container_name: mariadb
      image: mariadb:10.5.2
      ports:
         - "3306:3306"
      volumes:
         - "./database:/var/lib/mysql"
      restart: always
      environment:
         TZ: "Europe/Madrid"
         MYSQL_ROOT_HOST: "%"
         MYSQL_ROOT_PASSWORD: "super"
         MYSQL_ALLOW_EMPTY_PASSWORD: "no"
         MYSQL_DATABASE: 'testdatabase'
         MYSQL_USER: 'super'
         MYSQL_PASSWORD: 'super'

   phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      links: 
         - mariadb:db
      ports:
         - 8080:80
      environment:
         PMA_ARBITRARY: 1
         PMA_USER: super
         PMA_PASSWORD: super
   api:
    build:
      context: ./DocumentRoot/api
      dockerfile: Dockerfileapi
    container_name: fastapi
    ports:
      - '8000:8000'
    volumes:
      - ./DocumentRoot/api:/app
         
  
