version: '3.8'
services:
   php-httpd:
      container_name: php
      build: "./"
      image: php:8.1-apache
      expose:
         - 80
      ports:
         - 80:80
      volumes:
         - "./DocumentRoot/app/:/var/www/html"
         
   mariadb:
      container_name: mariadb
      image: mariadb:latest
      ports:
         - "3306:3306"
      volumes:
         - "./database/mariadb:/var/lib/mysql"
      environment:
         MYSQL_ROOT_HOST: "%"
         MYSQL_ROOT_PASSWORD: "admin"
         MYSQL_ALLOW_EMPTY_PASSWORD: "no"
         MYSQL_DATABASE: 'testdatabase'
         MYSQL_USER: 'super'
         MYSQL_PASSWORD: 'super'

   phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
         - 8080:80
      environment:
         PMA_HOST: mariadb
         PMA_USER: super
         PMA_PASSWORD: super
   api:
      container_name: fastapi
      build:
         context: ./DocumentRoot/api
         dockerfile: Dockerfileapi
      ports:
         - '8000:8000'
      volumes:
         - ./DocumentRoot/api:/app